development:
  adapter: postgresql
  database:
  username: lanxi
  password: passwd
  host: localhost
  pool: 5

test:
  adapter: postgresql
  database:
  username: lanxi
  password: passwd
  host: localhost
  pool: 5

production:
  adapter: postgresql
  database:
  username:
  password: 
  host: localhost